apiVersion: v2
actions:
  - name: "Be polite and say hello!"
    events:
      - name: "sh.keptn.event.remote-task.triggered"
    tasks:
      - name: "remote-simulation"
        image: "annadreal/myfmu:latest"
        args:
          - 1 1 1