apiVersion: v2
actions:
  - name: "Running thermal simulation"
    events:
      - name: "sh.keptn.event.remote-simulation.triggered"
    tasks:
      - name: "remote-simulation"
        image: "annadreal/myfmu:latest"
        args: ["$(LABELS_TEMPERATURE)","10","10"]
