apiVersion: v2
actions:
  - name: "Running thermal simulation"
    events:
      - name: "sh.keptn.event.remote-simulation.triggered"
    tasks:
      - name: "remote-simulation"
        image: "annadreal/passfmu:latest"
        args:
          - $(TEMPERATURE)
          - $(FLOW)
          - $(PRESSURE)
        env:
          - name: TEMPERATURE
            value: "$.data.labels.temperature"
            valueFrom: event
          - name: FLOW
            value: "$.data.labels.flow"
            valueFrom: event
          - name: PRESSURE
            value: "$.data.labels.pressure"
            valueFrom: event
