apiVersion: v2
actions:
  - name: "Running thermal simulation"
    events:
      - name: "sh.keptn.event.remote-simulation.triggered"
    tasks:
      - name: "remote-simulation"
        image: "annadreal/myfmu:latest"
        args: ["$(TEMPERATURE)","$(FLOW)","$(PRESSURE)"]
        env:
        - name: TEMPERATURE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['temperature']
        - name: FLOW
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['flow']
        - name: PRESSURE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pressure']
